# Use official Python image as base
FROM python:3.12.3

# Install system dependencies for Azure Speech SDK
RUN apt-get update && apt-get install -y \
    libasound2 \
    && rm -rf /var/lib/apt/lists/*



# Set the working directory inside the container
WORKDIR /app

# Copy only requirements.txt first (for efficient caching)
COPY requirements.txt .



# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Python dependencies
RUN pip install azure-cognitiveservices-speech

# Copy the rest of the frontend code into the container
COPY . .

# Expose the port Streamlit runs on
EXPOSE 8501

# Command to run the Streamlit app
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
