version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env  # Load environment variables for Azure keys
    volumes:
      - ./backend:/app  # Sync local changes for development
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend  # Ensures the backend starts before the frontend
    volumes:
      - ./frontend:/app  # Sync local changes for development
    restart: always
